# Generated by Django 5.2.1 on 2025-05-29 19:26

import plots.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Plot',
            fields=[
                ('plot_id', models.CharField(default=plots.models.generate_plot_id, max_length=20, primary_key=True, serialize=False)),
                ('plot_name', models.CharField(max_length=100)),
                ('plot_location', models.CharField(max_length=255)),
                ('plot_size', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
